### ISSUE TITLE
Can you share your email ?

### ISSUE THREAD

**Issue by JasurbekOripov** [KostasZigo/Web-Android-WebRTC-app#1]
Hello, i was struggling to do video call and spend around a month and your solution worked fine for me. I wanted to buy you coffee but i could not find a link or email. If it is possible put a link to buy a coffee. Thank you bro for this open source project.

**Comment by KostasZigo** [comment]
Hello, thanks for your kind words, you really made my day!! But really bro, you don't have to buy me anything. Don't get me wrong, I really appreciate the gesture, but I am more than happy to help without the reward. I am very glad that this project helped you progress, I hope you are building great thinks bro!!!

You can for sure have my email though: kzygogiannis.mpl@gmail.com

P.S. credits to my team as well, as I did not build this project alone 
[Konstantinos Kyratsous](https://github.com/KonstantinosKyratsous)
[Vasiliki Kanakari](https://github.com/vasilikikan)
